### ISSUE TITLE
Raspberry Pi 4 image 

### ISSUE THREAD

**Issue by ShlomiD83** [danielb7390/nut-cgi#1]
Hi,
Is there a way to create an image that'll work on RPi 4?

**Comment by danielb7390** [comment]
Added a rpi tag. Give it a try.
`docker pull danielb7390/nut-cgi:rpi`

**Comment by ShlomiD83** [comment]
> Added a rpi tag. Give it a try. `docker pull danielb7390/nut-cgi:rpi`

Hi, thanks for the quick reply.
the container is up and working but I get errros.
![image](https://user-images.githubusercontent.com/17053215/175799211-2632b28b-89c8-48bb-a628-e5034a6ab165.png)
![image](https://user-images.githubusercontent.com/17053215/175799219-331fb9c5-2cff-4148-8e56-553b8ecc0282.png)

**Comment by ShlomiD83** [comment]
thank you for the quick reply!
it works great now.

I just had to map "uppset.conf" to the container..

**Comment by ShlomiD83** [comment]
Can you build the image using alpine so it'll be more lightweight?

**Comment by danielb7390** [comment]
I had tried before but there's no `nut-cgi` package on alpine. The main `nut` package doesn't include the upsstats.cgi.

**Comment by ShlomiD83** [comment]
> I had tried before but there's no `nut-cgi` package on alpine. The main `nut` package doesn't include the upsstats.cgi.

I understand, thank you anyway.
it works great.
