### ISSUE TITLE
change timezone from UTC to localtime

### ISSUE THREAD

**Issue by ShlomiD83** [danielb7390/nut-cgi#2]
Hi again,
I've set an env variable to change TZ to my local time but nut-cgi always displays UTC time.
I've tried mapping a time zone file to the container but that didn't change the TZ.

how can I change the dashboard to display my local time?

**Comment by danielb7390** [comment]
Hi,
I'm not sure this is a docker problem. If i enter the docker container and run a `date` command it shows me the correct date and timezone when using the `TZ` variable.

I went looking in the source code of nut, and the part that generates the date is here: https://github.com/networkupstools/nut/blob/bce1d5201679e0dd64a839ceaaf47dc14c3c6a16/clients/upsstats.c#L195

It receives the parameters from the template here: https://github.com/networkupstools/nut/blob/03c3bbe8df9a2caf3c09c120ae7045d35af99b76/conf/upsstats.html.sample#L56

Not sure if it's a bug on their code, or if we are missing any configuration...

I actually never noticed the wrong time 😂

**Comment by ShlomiD83** [comment]
thanks for the quick reply.
it's not a big deal, just something I noticed.
